export const elencoReal = [
  {
    "Numero": "-",
    "Jogador": "CaÃ­que FranÃ§a",
    "Nacionalidade": "Brazil",
    "Altura": "186",
    "Idade": "30",
    "Posicao": "",
    "Partidas": "5",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "79.61",
    "Dribles": "0",
    "Desafios": "66.67",
    "Minutos": "505"
  },
  {
    "Numero": "-",
    "Jogador": "Jonathan Costa",
    "Nacionalidade": "Brazil",
    "Altura": "186",
    "Idade": "30",
    "Posicao": "",
    "Partidas": "5",
    "Gols": "1",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "89.5",
    "Dribles": "0",
    "Desafios": "41.67",
    "Minutos": "505"
  },
  {
    "Numero": "-",
    "Jogador": "Willian Farias",
    "Nacionalidade": "Brazil",
    "Altura": "177",
    "Idade": "36",
    "Posicao": "",
    "Partidas": "5",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "89.02",
    "Dribles": "0.2",
    "Desafios": "60",
    "Minutos": "454"
  },
  {
    "Numero": "-",
    "Jogador": "Emerson",
    "Nacionalidade": "Brazil",
    "Altura": "179",
    "Idade": "27",
    "Posicao": "",
    "Partidas": "5",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "71.81",
    "Dribles": "1.81",
    "Desafios": "60.49",
    "Minutos": "447"
  },
  {
    "Numero": "-",
    "Jogador": "Nathan Melo",
    "Nacionalidade": "Brazil",
    "Altura": "186",
    "Idade": "24",
    "Posicao": "",
    "Partidas": "5",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "92.08",
    "Dribles": "0.21",
    "Desafios": "63.08",
    "Minutos": "433"
  },
  {
    "Numero": "-",
    "Jogador": "Guilherme Parede",
    "Nacionalidade": "Brazil",
    "Altura": "178",
    "Idade": "30",
    "Posicao": "",
    "Partidas": "5",
    "Gols": "1",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "77.08",
    "Dribles": "1.61",
    "Desafios": "32",
    "Minutos": "391"
  },
  {
    "Numero": "-",
    "Jogador": "Raphael",
    "Nacionalidade": "Brazil",
    "Altura": "185",
    "Idade": "27",
    "Posicao": "",
    "Partidas": "5",
    "Gols": "1",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "77.57",
    "Dribles": "0.24",
    "Desafios": "51.52",
    "Minutos": "379"
  },
  {
    "Numero": "-",
    "Jogador": "Mirandinha",
    "Nacionalidade": "Brazil",
    "Altura": "179",
    "Idade": "26",
    "Posicao": "",
    "Partidas": "5",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "74.14",
    "Dribles": "5.77",
    "Desafios": "49.45",
    "Minutos": "359"
  },
  {
    "Numero": "-",
    "Jogador": "MaranhÃ£o",
    "Nacionalidade": "Brazil",
    "Altura": "183",
    "Idade": "29",
    "Posicao": "",
    "Partidas": "4",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "75",
    "Dribles": "1.04",
    "Desafios": "27.03",
    "Minutos": "345"
  },
  {
    "Numero": "-",
    "Jogador": "MaurÃ­cio AntÃ´nio",
    "Nacionalidade": "Brazil",
    "Altura": "183",
    "Idade": "33",
    "Posicao": "",
    "Partidas": "3",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "89.93",
    "Dribles": "0",
    "Desafios": "66.67",
    "Minutos": "302"
  },
  {
    "Numero": "-",
    "Jogador": "Isaque",
    "Nacionalidade": "Brazil",
    "Altura": "178",
    "Idade": "28",
    "Posicao": "",
    "Partidas": "4",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "82.61",
    "Dribles": "2.4",
    "Desafios": "38.24",
    "Minutos": "262"
  },
  {
    "Numero": "-",
    "Jogador": "Rafael Donato",
    "Nacionalidade": "Brazil",
    "Altura": "193",
    "Idade": "36",
    "Posicao": "",
    "Partidas": "2",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "72.22",
    "Dribles": "0",
    "Desafios": "48",
    "Minutos": "203"
  },
  {
    "Numero": "-",
    "Jogador": "Dentinho",
    "Nacionalidade": "Brazil",
    "Altura": "183",
    "Idade": "28",
    "Posicao": "",
    "Partidas": "5",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "87.5",
    "Dribles": "8.65",
    "Desafios": "41.46",
    "Minutos": "156"
  },
  {
    "Numero": "-",
    "Jogador": "Lucca",
    "Nacionalidade": "Brazil",
    "Altura": "178",
    "Idade": "35",
    "Posicao": "",
    "Partidas": "3",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "94.74",
    "Dribles": "1.78",
    "Desafios": "32.14",
    "Minutos": "152"
  },
  {
    "Numero": "-",
    "Jogador": "D. Torres",
    "Nacionalidade": "Argentina",
    "Altura": "174",
    "Idade": "35",
    "Posicao": "",
    "Partidas": "4",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "88.24",
    "Dribles": "0.6",
    "Desafios": "40",
    "Minutos": "150"
  },
  {
    "Numero": "-",
    "Jogador": "Cicinho",
    "Nacionalidade": "Brazil",
    "Altura": "168",
    "Idade": "37",
    "Posicao": "",
    "Partidas": "3",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "82.98",
    "Dribles": "4.29",
    "Desafios": "53.13",
    "Minutos": "126"
  },
  {
    "Numero": "-",
    "Jogador": "Guilherme Cachoeira",
    "Nacionalidade": "Brazil",
    "Altura": "167",
    "Idade": "23",
    "Posicao": "",
    "Partidas": "3",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "80",
    "Dribles": "8.09",
    "Desafios": "42.31",
    "Minutos": "89"
  },
  {
    "Numero": "-",
    "Jogador": "Renan Castro",
    "Nacionalidade": "Brazil",
    "Altura": "175",
    "Idade": "30",
    "Posicao": "",
    "Partidas": "2",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "84.21",
    "Dribles": "1.55",
    "Desafios": "33.33",
    "Minutos": "58"
  },
  {
    "Numero": "-",
    "Jogador": "Igor Pereira",
    "Nacionalidade": "Brazil",
    "Altura": "181",
    "Idade": "24",
    "Posicao": "",
    "Partidas": "1",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "62.5",
    "Dribles": "1.64",
    "Desafios": "50",
    "Minutos": "55"
  },
  {
    "Numero": "-",
    "Jogador": "KauÃ£ Jesus",
    "Nacionalidade": "Brazil",
    "Altura": "170",
    "Idade": "22",
    "Posicao": "",
    "Partidas": "2",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "0",
    "Dribles": "0",
    "Desafios": "0",
    "Minutos": "43"
  },
  {
    "Numero": "-",
    "Jogador": "Ralf",
    "Nacionalidade": "Brazil",
    "Altura": "182",
    "Idade": "41",
    "Posicao": "",
    "Partidas": "2",
    "Gols": "0",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "0",
    "Dribles": "0",
    "Desafios": "0",
    "Minutos": "43"
  },
  {
    "Numero": "-",
    "Jogador": "Kewen",
    "Nacionalidade": "Brazil",
    "Altura": "0",
    "Idade": "21",
    "Posicao": "",
    "Partidas": "2",
    "Gols": "1",
    "Assistências": "0",
    "Acoes_Sucesso": "0",
    "Passes_Precisos": "0",
    "Dribles": "0",
    "Desafios": "0",
    "Minutos": "33"
  }
];